#!/usr/bin/env zsh

set -x

PODMAN=$(command -v podman.exe 2> /dev/null)
if [ ! -z "$PODMAN" ]
then
	#Podman on WSL: Use short form to avoid whitespace in Program Files
  DOCKER='podman.exe'
else
	#Native docker installed
  DOCKER='docker'
fi

self_dir=$(dirname $0)
src_dir="${self_dir}/../src"
$DOCKER run --rm -v${src_dir:a}:/src kkrull/gcc:latest $@
